# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d0790c489c1d1df1f756ffcdfff06f10c9e9a6a24e861c5050d77e9ed8c5b0a3d3a6fbbab570e5b29f6905945bb85a6ce0c0c2abf4ff6f6d7d190ab968796f8

test:
  secret_key_base: 76dae7f5fbb29deeb4bd774673efd1c4f8bcfde1e02931e6a88cd84264d51eb6111079c0e467876c696796268c593fa4f09f16eb1672bb3b296a5896e2d4d386

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
